app/views/layouts/application.html.erb
=> conflict_nakahashi

config/routes.rb
=> [Add]routes修正

app/controllers/admin/genres_controller.rb, app/models/genre.rb, app/views/admin/genres/_form.html.erb, app/views/admin/genres/_index.html.erb, app/views/admin/genres/edit.html.erb, db/migrate/20221218044132_create_genres.rb, db/schema.rb, test/fixtures/genres.yml, test/models/genre_test.rb
=> [Add]genre追加

app/models/order.rb, app/views/admin/genres/edit.html.erb, db/migrate/20221218091645_create_orders.rb, test/fixtures/orders.yml, test/models/order_test.rb
=> [Add]genre編集画面修正

app/models/customer.rb, db/schema.rb
=> [Fix]会員登録編集

app/controllers/admin/customers_controller.rb, app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb
adminのcustomers関連を追加しました。
・会員一覧
・adminによる会員情報の閲覧・編集
=> Feature admin customers

app/controllers/public/cart_items_controller.rb, app/controllers/public/items_controller.rb, app/models/cart_item.rb, app/models/customer.rb, app/views/public/cart_items/index.html.erb, app/views/public/items/show.html.erb, config/routes.rb, db/migrate/20221220044224_create_cart_items.rb, db/schema.rb, test/fixtures/cart_items.yml, test/models/cart_item_test.rb
public/item,cart_item機能の追加（一覧機能等、一部未完成）
=> Feature cart items

app/views/public/cart_items/index.html.erb
=> [Update]カート内閲覧のレイアウト調整、合計金額の追加

Gemfile, Gemfile.lock, app/controllers/admin/homes_controller.rb, app/controllers/public/orders_controller.rb, app/models/customer.rb, app/models/item.rb, app/models/order.rb, app/models/order_detail.rb, app/models/shipping_address.rb, app/views/admin/orders/show.html.erb, app/views/public/orders/complete.html.erb, app/views/public/orders/confirm.html.erb, app/views/public/orders/index.html.erb, app/views/public/orders/new.html.erb, app/views/public/orders/show.html.erb, config/application.rb, config/locales/ja.yml, config/routes.rb, db/migrate/20221218091645_create_orders.rb, db/migrate/20221222084013_create_order_details.rb, db/schema.rb, test/fixtures/order_details.yml, test/models/order_detail_test.rb
=> Feature order

Gemfile, Gemfile.lock, app/controllers/admin/customers_controller.rb, app/controllers/admin/items_controller.rb, app/controllers/public/items_controller.rb, app/views/admin/customers/index.html.erb, app/views/admin/items/index.html.erb, app/views/kaminari/_first_page.html.erb, app/views/kaminari/_gap.html.erb, app/views/kaminari/_last_page.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/public/items/index.html.erb, config/initializers/kaminari_config.rb
ページネーション追加。
・admin・・・商品一覧、会員一覧追加。（注文履歴一覧未追加）
・customer・・・商品一覧。
=> Feature pagination

app/controllers/public/items_controller.rb
=> [Fix]publicの商品一覧の商品件数を販売中のみに修正

app/views/layouts/_footer.html.erb, app/views/layouts/application.html.erb
=> [Add]footerの追加

app/views/public/orders/index.html.erb
=> [Add]注文履歴一覧商品名修正

app/controllers/admin/homes_controller.rb, app/controllers/public/orders_controller.rb, app/views/admin/homes/top.html.erb, app/views/public/orders/index.html.erb
public・adminの注文履歴一覧でのページネーション追加
=> [Update]public・adminの注文履歴一覧でのページネーション追加

app/controllers/admin/customers_controller.rb, app/controllers/admin/genres_controller.rb, app/controllers/admin/items_controller.rb, app/controllers/admin/order_details_controller.rb, app/controllers/admin/orders_controller.rb, app/controllers/application_controller.rb, app/controllers/public/cart_items_controller.rb, app/controllers/public/customers_controller.rb, app/controllers/public/orders_controller.rb, app/controllers/public/shipping_addresses_controller.rb, app/views/admin/sessions/new.html.erb, app/views/public/sessions/new.html.erb
=> Feature sign in

app/controllers/admin/items_controller.rb, app/controllers/admin/searches_controller.rb, app/controllers/public/searches_controller.rb, app/models/item.rb, app/views/admin/items/_form.html.erb, app/views/admin/searches/_search.html.erb, app/views/admin/searches/search.html.erb, app/views/layouts/_admin_header.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/_public_header.html.erb, app/views/public/searches/_search.html.erb, app/views/public/searches/search.html.erb, config/routes.rb
検索機能の追加。
・商品名での検索機能追加。
※ジャンルでの検索は未実装。
=> Feature search

app/controllers/admin/orders_controller.rb, app/views/admin/orders/customer.html.erb, app/views/admin/orders/show.html.erb, config/routes.rb
=> [Finish]顧客ごとの注文履歴完成

app/views/layouts/_admin_header.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/_public_header.html.erb
=> [Fix]ヘッダーレイアウト修正

app/views/admin/customers/index.html.erb
=> [Fix]adminの会員一覧のレイアウト調整

app/views/public/items/index.html.erb
=> [Fix]ページネーションの位置修正

app/views/layouts/_admin_header.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/_public_header.html.erb
=> [Add]headerレイアウト変更
